cognitive-complexity-threshold = 10
too-many-arguments-threshold = 4
too-many-lines-threshold = 50
excessive-nesting-threshold = 4

pass-by-value-size-limit = 256
stack-size-threshold = 131072
enum-variant-size-threshold = 128
vec-box-size-threshold = 256

type-complexity-threshold = 200
literal-representation-threshold = 16
max-trait-bounds = 4
enum-variant-name-threshold = 3

warn-on-all-wildcard-imports = true
avoid-breaking-exported-api = false
too-large-for-stack = 4096
accept-comment-above-attributes = true

allow-unwrap-in-tests = true
allow-expect-in-tests = true
