name: mutation

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-mutants
        run: cargo install --locked cargo-mutants

      - name: Run mutation tests
        run: cargo mutants --package snowid --file src/generator --file src/config --file src/extractor -- --tests
